name: ✨New example
description: Submit a new example to be added to the repository
title: 'New example: <title>'
labels: [✨ New example]
body:
  - type: markdown
    attributes:
      value: '# Example submission'
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the example is, how useful it is.
      placeholder: This example shows how to...
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure you have done all of this before submitting!
      options:
        - label: "I've followed all of [the best practices](https://wiki.gdevelop.io/gdevelop5/community/guide-for-submitting-an-example)."
          required: true
        - label: My game has a proper name in the game properties.
          required: true
        - label: My game package name begins with `com.example.`.
          required: true
        - label: My game has all events unfolded.
          required: true
        - label: I've added myself as the author in the game properties.
          required: true
        - label: I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
          required: true
        - label: I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
          required: true
        - label: I've cleaned unused resources.
          required: true
  - type: textarea
    id: example
    attributes:
      label: Game project folder
      description: Please drag into this text field a zip file containing your game project folder and all its resources (images, sounds, etc...). **DO NOT PUT A LINK TO AN EXTERNAL SERVICE LIKE GOOGLE DRIVE!**
      placeholder: '[MyExample.zip]()'
    validations:
      required: true
  - type: textarea
    id: preview
    attributes:
      label: Game preview
      description: You can add a few screenshots of your game and a link to play it to show how cool your example is.
      placeholder: 'Try my game on gd.games...'
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If your game is high quality and useful, it will be added to the list of GDevelop community examples.
        Thanks for contributing to GDevelop! 🙌